// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpshyibloyrgldaeufqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxwc2h5aWJsb3lyZ2xkYWV1ZnFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTE2MzUsImV4cCI6MjA2MTA2NzYzNX0.GF0XgQFm3utJwss_uNe2hhBr71cEFEq3JOOxpMe1tnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);